### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by unscriptable** [paradoxxxzero/next-occurrence#1]
[Enter steps to reproduce below:]
1. Place cursor in a word, but _do not_ select any characters.
2. Press the key combination for next-occurrence:next or next-occurrence:prev.

Note: I remapped the keybindings like this:

``` cson
'.editor':
  'cmd-f6': 'next-occurrence:next'
  'cmd-shift-f6': 'next-occurrence:prev'
```

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [next-occurrence](https://github.com/paradoxxxzero/next-occurrence) package, v0.3.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/john/.atom/packages/next-occurrence/lib/next-occurrence.coffee:18

TypeError: undefined is not a function
  at Object.module.exports.init (/Users/john/.atom/packages/next-occurrence/lib/next-occurrence.coffee:18:43)
  at atom-workspace.<anonymous> (/Users/john/.atom/packages/next-occurrence/lib/next-occurrence.coffee:7:8)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
     -1:14.7 core:move-up (atom-text-editor.editor)
  6x -1:14.6 core:move-left (atom-text-editor.editor)
     -1:13.4 core:backspace (atom-text-editor.editor)
     -1:09.7 editor:consolidate-selections (atom-text-editor.editor)
     -1:09.7 core:cancel (atom-text-editor.editor)
     -1:08.7 core:save (atom-text-editor.editor)
 10x -1:04.0 next-occurrence:prev (atom-text-editor.editor.is-focused)
     -0:24.1 core:move-down (atom-text-editor.editor)
  2x -0:23.6 editor:move-to-end-of-word (atom-text-editor.editor)
     -0:23.1 editor:select-to-end-of-word (atom-text-editor.editor)
     -0:21.5 core:save (atom-text-editor.editor)
  2x -0:17.7 next-occurrence:next (atom-text-editor.editor.is-focused)
     -0:05.9 next-occurrence:prev (atom-text-editor.editor.is-focused)
     -0:05.2 next-occurrence:next (atom-text-editor.editor.is-focused)
     -0:04.4 next-occurrence:prev (atom-text-editor.editor.is-focused)
     -0:00.3 next-occurrence:next (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "language-objective-c",
      "language-coffee-script",
      "language-csharp",
      "language-java",
      "language-make",
      "language-mustache",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-toml",
      "autohide-tree-view",
      "autocomplete",
      "symbols-view"
    ],
    "projectHome": "~/NoWait",
    "ignoredNames": [
      ".git",
      ".DS_Store"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.6.0
find-selection, v0.14.0
ide-haskell, v0.3.6
jsdoc, v0.9.0
language-haskell, v1.0.0
next-occurrence, v0.3.0
open-last-project, v0.3.5
tabs-to-spaces, v0.9.0

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Hey, I just updated this package to fix deprecated calls to Atom's API. Does the updated version (`v0.4.0`) fix this problem?

**Comment by unscriptable** [comment]
Sorry, I wasn't coding for a while (design/documentation phase).  Just tried it and it seems to work great!  Thanks!

**Comment by olmokramer** [comment]
No worries :) Thanks for letting me know!
